# Generated by Django 4.2.1 on 2023-12-21 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prediccion', '0002_rename_archivo_entrenamiento_modeloprediccion_archivo_entrenamiento_excel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptPrediccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
