# Generated by Django 4.2.1 on 2023-12-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prediccion', '0003_scriptprediccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptprediccion',
            name='motivo_descarte',
            field=models.TextField(blank=True, null=True),
        ),
    ]
