# Generated by Django 5.0 on 2023-12-14 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='user',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='user',
        ),
        migrations.DeleteModel(
            name='PassRecover',
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.DeleteModel(
            name='Verification',
        ),
    ]
